Objects event filter
Azure/live-video-analytics pull request #199
Opened 2021-03-30 13:17 UTC by fvneerden

2021-03-30 13:18 UTC, fvneerden commented
#sign-off

2021-03-31 18:55 UTC, anilmur requested changes
Comments/corrections provided. Thanks

2021-03-31 18:55 UTC, anilmur commented on MediaGraph/topologies/grpcExtensionOpenVINO/2.0/readme.md
> +# Analyzing live video using gRPC Extension to send images to the OpenVINO(TM) DL Streamer - Edge AI Extension module from Intel
Why is this file part of the PR? There is already a readme.md in https://github.com/Azure/live-video-analytics/tree/master/MediaGraph/topologies/grpcExtensionOpenVINO/2.0/

2021-03-31 18:55 UTC, anilmur commented on MediaGraph/topologies/grpcExtensionOpenVINO/2.0/topology.json
> +{
Why is this part of the PR? There is already a topology JSON in https://github.com/Azure/live-video-analytics/tree/master/MediaGraph/topologies/grpcExtensionOpenVINO/2.0/

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/Dockerfile.amd64
> +FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env
It would be better to put objectEventsFilter under https://github.com/Azure/live-video-analytics/tree/master/utilities/

This module by itself is not a ref app.

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/Program.cs
> +        private static async Task OnDesiredPropertyChanged(TwinCollection desiredProperties, object userContext)
Add a brief line about what this method does

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/Program.cs
> +                throw new InvalidOperationException("UserContext doesn't contain " + "expected values");
Nit - why break the string with a + here?

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +This edge module can be deployed to your IoT Edge device that runs the Live Video Analytics pipeline and trigger a recording based on certain inference attributes. While it is written to work with in
The objectEventsFilter module can be ...

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +This edge module can be deployed to your IoT Edge device that runs the Live Video Analytics pipeline and trigger a recording based on certain inference attributes. While it is written to work with in
Also, these are LVA docs, so avoid talking about pipeline. Use "media graph"!!

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +This edge module can be deployed to your IoT Edge device that runs the Live Video Analytics pipeline and trigger a recording based on certain inference attributes. While it is written to work with in
Instead of:
   it can also be used and modified to work with YOLO/DeepStream since the code is open source.

Use

   it can also be modified for use with any other AI module listed in https://github.com/Azure/live-video-analytics/tree/master/utilities/video-analysis/. This sample code is currently...

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +<img src="./images/evr-pipeline.svg" title="LVA objectsEventFilter module on IoT Edge"/>
Title is: "LVA with Intel DL Streamer - Edge AI Extension and objectEventFilter modules"

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +The RTSP source will split video into a Signal Gate which will hold back the video flow and the gRPC Extension which will create images out of the video and feed to the AI Inference service. the gRPC
Recommend using the text from our tutorial https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/event-based-video-recording-tutorial. Please edit the text appropriately:



The first path is to a HTTP extension node. The node samples the video frames to a value set by you using the samplingOptions field and then relays the frames, as images, to the AI module YOLOv3, which is an object detector. The node receives the results, which are the objects (vehicles in traffic) detected by the model. The HTTP extension node then publishes the results via the IoT Hub message sink node to the IoT Edge hub.
The objectCounter module is set up to receive messages from the IoT Edge hub, which include the object detection results (vehicles in traffic). The module checks these messages and looks for objects of a certain type, which were configured via a setting. When such an object is found, this module sends a message to the IoT Edge hub. Those "object found" messages are then routed to the IoT Hub source node of the media graph. Upon receiving such a message, the IoT Hub source node in the media graph triggers the signal gate processor node. The signal gate processor node then opens for a configured amount of time. Video flows through the gate to the asset sink node for that duration. That portion of the live stream is then recorded via the asset sink node to an asset in your Azure Media Services account.

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +1) Clone this repo to your development machine where you also have the LVA tutorials repo cloned
Provide a link to the tutorials repo

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +Now that you have the module pushed to your Azure Container Registry you can create a deployment manifest that will reference it and deploy it to your LVA IoT Edge device. A sample template is includ
... reference it and deploy it to your IoT Edge device.

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/readme.md
> +Pay attentention to to the bottom part of the template. This is where you specify the attribute values and confidence level to trigger on.
attentention :-)

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/templates/deployment.objectsEventFilter.template.json
> +              "image": "intel/video-analytics-serving:0.4.1-dlstreamer-edge-ai-extension",
Is the image path correct??

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/templates/deployment.objectsEventFilter.template.json
> +        },
These routing rules are an important part of the setup. Recommend you touch upon them in the readme.md

2021-03-31 18:55 UTC, anilmur commented on ref-apps/objectsEventFilter/templates/deployment.objectsEventFilter.template.json
> +        "objectTypeValue": "truck",
white van, to be consistent with the rest of the docs?

2021-03-31 18:55 UTC, anilmur commented on utilities/video-analysis/readme.md
> +| `dl-streamer`        | OpenVINO™ DL Streamer – Edge AI Extension from Intel                     |
No need to modify this, the line already exists in master branch

2021-04-01 07:42 UTC, closed without merging

2021-04-01 07:55 UTC, fvneerden commented on MediaGraph/topologies/grpcExtensionOpenVINO/2.0/readme.md
> +# Analyzing live video using gRPC Extension to send images to the OpenVINO(TM) DL Streamer - Edge AI Extension module from Intel
Not sure, this shoudn't be here. I rebased my repo so when I do a compare now it is not showing this file as changed anymore. So that seems fixed.

2021-04-01 07:55 UTC, fvneerden commented on MediaGraph/topologies/grpcExtensionOpenVINO/2.0/topology.json
> +{
Not sure, this shoudn't be here. I rebased my repo so when I do a compare now it is not showing this file as changed anymore. So that seems fixed.

2021-04-01 07:56 UTC, fvneerden commented on ref-apps/objectsEventFilter/Dockerfile.amd64
> +FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env
Really? This is what was told me as the location (by you). I will move it.